*** Variables ***
${title_checkout_step_two_element}   css=[data-test="title"]
${payment_info_label_element}        css=[data-test="payment-info-label"]
${shipping_info_label_element}       css=[data-test="shipping-info-label"]
${total_info_label_element}          css=[data-test="total-info-label"]
${tax_label_element}                 css=[data-test="tax-label"]
${subtotal_label_element}            css=[data-test="subtotal-label"]
${total_label_element}               css=[data-test="total-label"]
${finish_button_element}             id=finish
